### ISSUE TITLE
Hide trailing signature public key on return from the default CMM

### ISSUE THREAD

**Issue by bdonlan** [aws/aws-encryption-sdk-c#197]
This key is not of any use to client code, and makes it more difficult to verify that the encryption context is the same from encrypt to decrypt. We should redact it from the context before returning from the default CMM.

**Comment by robin-aws** [comment]
As per awslabs/aws-encryption-sdk-specification#4, I'm currently inclined not to do this and instead make it easier for customers to verify the expected EC using the ESDK API.

**Comment by alex-chew** [comment]
Closing in favor of the specification change proposal.
