### ISSUE TITLE
KMS keyring's "aws-kms" string should be optimized

### ISSUE THREAD

**Issue by david-koenig** [aws/aws-encryption-sdk-c#221]
Should be created with AWS_STATIC_STRING_FROM_LITERAL and that string should be propagated into trace still in static form.

**Comment by robin-aws** [comment]
Pulling this into spec alignment milestone in case "trace" here refers to the keyring trace, which is being removed

**Comment by david-koenig** [comment]
This does not refer to the keyring trace, or at least not only to the keyring trace. The string "aws-kms" is used in at least one of the metadata fields of the EDK's used by KMS. There is a macro in aws-common called `AWS_STATIC_STRING_FROM_LITERAL` which allows you to define a static string such that all copies to it are pointers to the same static string. See string.cpp in the examples directory and some other examples for that macro being used.

The problem is that the KMS keyring code was originally written in C++ not using the aws-c-common library for string handling. The strings were defined as C++ objects and only later converted to aws_string type in the C code. The change here is to refactor the C++ code so that the "aws-kms" string specifically is originally defined by `AWS_STATIC_STRING_FROM_LITERAL("aws-kms")` instead of as a C++ string. This will ensure that no internal copies of the "aws-kms" string will be made either in the C++ or C code.

**Comment by robin-aws** [comment]
Got it, thanks for the clarification @david-koenig!

**Comment by david-koenig** [comment]
One further clarification I should make is that the keyring trace causes a lot of extra copies of the "aws-kms" string to be made. (One for every KMS call to encrypt or decrypt with every KMS key involved in a particular encryption. Whereas without the keyring trace, the number of copies of the string would only be the total number of keys used, not the total number of times they were called.) So *if* the keyring trace is being removed, this may be a less important optimization. However, with the keyring trace still in there, the value of the optimization is higher.

**Comment by robin-aws** [comment]
Good to know - the keyring trace is definitely being removed (#548 - PR already in the works) so it sounds like this is a lower priority.

**Comment by alex-chew** [comment]
Closing as the only non-keyring-trace usage does not make a copy of the string.
