### ISSUE TITLE
git sub-module for aws-encryption-sdk-test-vectors package

### ISSUE THREAD

**Issue by ttjsu-aws** [aws/aws-encryption-sdk-c#225]

**Comment by robin-aws** [comment]
To clarify (thanks @ttjsu-aws), the entry point to handle the test vectors is implemented (https://github.com/aws/aws-encryption-sdk-c/blob/master/aws-encryption-sdk-cpp/tests/test_vectors/static_test_vectors.cpp) but only run manually - you currently have to download the test vectors yourself to run them.

Technically this change would just make it easier to run the test vectors manually, but we should probably immediately add them to the CI (#414) if we're going to bother doing this.
