### ISSUE TITLE
Test aws_cryptosdk_alg_props(NULL)

### ISSUE THREAD

**Issue by bdonlan** [aws/aws-encryption-sdk-c#238]
We are missing coverage on https://github.com/awslabs/aws-encryption-sdk-c/blob/5b77a0a9b7131ffd3f32b6057cf42bfeaf0315b3/source/cipher.c#L67

Probably this is not covered because header.c has a (duplicate) function which determines if an algorithm is known; these should be consolidated, and then the existing tests should handle this case.

**Comment by alex-chew** [comment]
Closing as the function is tested under CBMC.
