### ISSUE TITLE
Add test for excessively large encryption context during header serialization

### ISSUE THREAD

**Issue by bdonlan** [aws/aws-encryption-sdk-c#241]
We have some missing coverage on codepaths that should be hit by serializing a header with 2^16 (or more) context keys. Specifically:

https://github.com/awslabs/aws-encryption-sdk-c/blob/5b77a0a9b7131ffd3f32b6057cf42bfeaf0315b3/source/enc_context.c#L35-L37
https://github.com/awslabs/aws-encryption-sdk-c/blob/5b77a0a9b7131ffd3f32b6057cf42bfeaf0315b3/source/header.c#L269-L271

**Comment by alex-chew** [comment]
Closing as complete: https://github.com/aws/aws-encryption-sdk-c/blob/84befdfabf0e635d43ffc107ca8f97a2c0eb77cf/tests/unit/t_enc_ctx.c#L271
