### ISSUE TITLE
Better cross-platform compatibility for style checking

### ISSUE THREAD

**Issue by david-koenig** [aws/aws-encryption-sdk-c#322]
Current clang-format style check only works if you run `reformat.sh` script on Linux, not on Mac. Investigate reason for incompatible formatting with clang-format on Mac and see if we can fix this by modifying `.clang-format` file or using different version of the software.

Also investigate installing clang-format on Windows and whether we can get the same formatting there.

Failing better compatibility with clang-format, consider using a different style checker.

**Comment by dougch** [comment]
Versions to repro the failure?

On MacOS `10.12.6`, with clang-format installed from brew (date stamped 2019-01-18), reformat runs successfully (tagged v1.0.0)

**Comment by danielsn** [comment]
It runs successfully, but it causes changes that are then rejected by the formatter in CI. https://github.com/aws/aws-encryption-sdk-c/pull/426

**Comment by danielsn** [comment]
Also, it doesn't enforce braces around if statements, which was specified as house style in https://github.com/aws/aws-encryption-sdk-c/pull/424
