### ISSUE TITLE
FIPS 140-2 support

### ISSUE THREAD

**Issue by varnerac** [aws/aws-encryption-sdk-c#358]
Will this SDK support OpenSSL in FIPS 140-2 mode? The AWS KMS offering uses FIPS 140-2 crypto. I think it’d make sense to keep FIPS compliance as an option in the SDK.

**Comment by arealjim** [comment]
Thanks for reaching out, Andrew!  We are investigating your question and will reply back on this thread when we have made a determination.  We appreciate your patience.

**Comment by texastony** [comment]
Andrew,

Our apologies for not getting back to you. At this time, the Encryption-SDK is not FIPS validated. FIPS validation is not on our roadmap.

Tony
