### ISSUE TITLE
check whether there is a latency issue with KMS keyring tests on Windows

### ISSUE THREAD

**Issue by david-koenig** [aws/aws-encryption-sdk-c#369]
This is an investigative task which may be looking for a problem that no longer exists in the code, so there may be nothing to fix, but we should still give it due diligence.

Notes from back in February indicated that some users might have experienced slowness in running some of the KMS keyring tests on Windows platform. We have not seen this on other platforms.

FYI, t_kms_keyring.cpp should not be reaching out to the network (but should fully mock the calls to KMS) but t_integration_kms_keyring.cpp should actually reach out to KMS.

**Comment by dougch** [comment]
Windows codebuild run from today:
```
2/24 Test  #3: t_kms_keyring.test ..................   Passed    0.09 sec
```
vs Ubuntu
```
2/22 Test  #2: t_kms_keyring.test ...............   Passed    0.12 sec
```
