### ISSUE TITLE
Incorporate the decrypt test vector into CI

### ISSUE THREAD

**Issue by seebees** [aws/aws-encryption-sdk-c#414]
Test vectors here:
https://github.com/awslabs/aws-encryption-sdk-test-vectors

**Comment by robin-aws** [comment]
To clarify (thanks @ttjsu-aws), the entry point to handle the test vectors is implemented (https://github.com/aws/aws-encryption-sdk-c/blob/master/aws-encryption-sdk-cpp/tests/test_vectors/static_test_vectors.cpp) but only run manually - you currently have to download the test vectors yourself to run them.
