### ISSUE TITLE
Example in aws-encryption-sdk-c crash in buffer byte_buf.h file. 

### ISSUE THREAD

**Issue by hectoregm** [aws/aws-encryption-sdk-c#429]
I have compiled the C++ SDK and encryption SDK as per github readme text. Compilation is successful , but when execute examples , the core dump. As the traces are in functions for encryption/decryption, I think the authentication has been successful. These crashes seems to be in buffer management . Do I need to set buffer management or something related to it. I have tried it on Ubuntu 16.04 ( openssl 1.0.2g) and Ubuntu 18.04 (openssl 1.1.0g) . Both have same results.

file_stream example Fatal error condition occurred in /usr/local/include/aws/common/byte_buf.h:511: aws_byte_buf_is_valid(buf)
Exiting Application
0x00007fa8404c9ae1: ?? ??:0
0x000000000001bea2: aws_byte_cursor_from_buf at byte_buf.h:513
0x000000000001cd36: aws_cryptosdk_priv_try_decrypt_body at session_decrypt.c:237
0x00007fa84096a092: ?? ??:0
0x0000000000004e7e: _ZL12process_filePKcS0_18aws_cryptosdk_modeS0_P13aws_allocator at file_streaming.cpp:?
0x000000000000539c: main at ??:?
0x00007fa83f647b97: ?? ??:0
0x000000000000477a: _start at ??:?
Aborted (core dumped)

Also string example Fatal error condition occurred in /usr/local/include/aws/common/byte_buf.h:802: aws_byte_buf_is_valid(output)
Exiting Application
0x00007fcd76937ae1: ?? ??:0
0x0000000000011599: aws_byte_buf_advance at byte_buf.h:803
0x0000000000012647: aws_cryptosdk_hdr_write at header.c:305
0x000000000001e024: sign_header at session_encrypt.c:189
0x000000000001dbd2: aws_cryptosdk_priv_try_gen_key at session_encrypt.c:98
0x00007fcd76b770c7: ?? ??:0
0x0000000000004f18: _Z14encrypt_stringP13aws_allocatorPKcPhmPmPKhmP14aws_hash_table at string.cpp:74
0x00000000000055ef: main at string.cpp:222
0x00007fcd75fbcb97: ?? ??:0
0x000000000000490a: _start at ??:?
Aborted (core dumped)

**Comment by ttjsu-aws** [comment]
Hi, What tagged version of aws-sdk-cpp  and aws-c-common are you using?

**Comment by hectoregm** [comment]
I used master for aws-sdk-cpp

**Comment by hectoregm** [comment]
Rebuild using tag 1.7.108 and the example worked

**Comment by karlw00t** [comment]
AWS C Common can be unstable at master. The best thing to do right now is to build with a specific version of AWS C common. Is there a feature or change you need in the newer version?

**Comment by dougch** [comment]
closing in favor of issue #450
