### ISSUE TITLE
Change refcount down to acquire-release ordering 

### ISSUE THREAD

**Issue by nchong-at-aws** [aws/aws-encryption-sdk-c#432]
Formal analysis shows that release atomics are not sufficient to prevent the bad behavior given in the comment for `aws_cryptosdk_private_refcount_down`, which we include here:

```
     * Memory ordering note: We must use release memory order here. Otherwise, we have the following race:
     *
     * Program order:
     *
     * Thread A:
     *   Release(obj) [if down() { free(obj) } ]
     *
     * Thread B:
     *   obj->foo = 1;
     *   Release(obj)
     *
     * Execution order:
     *
     * Thread B: down() -> false
     * Thread A: down() -> true
     * Thread A: free(obj)
     * Thread B: obj->foo = 1
     *
     * To prevent this we use release order, which forbids any memory accesses coming before this point
     * from being reordered later. This prevents thread B from reordering the obj->foo access to come after
     * the down().
```

The problem is that C11 does not give a happens-before relation between a write-release and a relaxed read. The read must be (at least) an acquire as well. A sufficient change is to strengthen the `atomic_fetch_sub_explicit` atomic to use `aws_memory_order_acq_rel`.

## In more detail

The herd model checker (https://github.com/herd/herdtools7) can take simple programs and analyze them against a formalized memory model such as for C11 (http://multicore.doc.ic.ac.uk/overhauling/) and exhaustively list all of the allowed behaviors of the program.

The following is an encoding of the bad condition in the comment:

```
C esdk-refcount
{ [refcount] = 2; [is_null] = 0; }

P0 (atomic_int* refcount, atomic_int* is_null) {
  int r0 = atomic_fetch_sub_explicit(refcount, 1, memory_order_release);
  if (r0 == 1) atomic_store_explicit(is_null, 1, memory_order_relaxed); // model free(obj)
}

P1 (atomic_int* refcount, atomic_int* is_null) {
  int p1_uses_null = atomic_load_explicit(is_null, memory_order_relaxed); // model using obj->foo (can it read NULL?)
  int r1 = atomic_fetch_sub_explicit(refcount, 1, memory_order_release);
}

exists(refcount=0 /\ is_null=1 /\ 0:r0=1 /\ 1:r1=2 /\ 1:p1_uses_null=1)
```

The line under `C esdk-refcount` gives the initial values in memory. I’ve modeled the case where the `refcount` is 2 and the object is not null (modeled by `is_null=0`). The other variables are used as follows:
 
  - `r0` will store the old value of refcount before the atomic decrement of P0 (aka Thread A in the comment)
  - `r1` will store the old value of refcount before the atomic decrement of P1 (aka Thread B in the comment)
  - `p1_uses_null` is the read of obj which models whether Thread B will use a free’d pointer
 
The critical question is whether it is possible for `p1_uses_null==1` with `r0==1` and `r1==2` (meaning the refcount decrements go Thread B then Thread A) encoded in the “exists” statement.

We can run herd over the program (the `-c11` flag means use the formal C11 memory model):

```
Test esdk-refcount Allowed
States 3
0:r0=1; 1:p1_uses_null=0; 1:r1=2; is_null=1; refcount=0;
0:r0=1; 1:p1_uses_null=1; 1:r1=2; is_null=1; refcount=0;
0:r0=2; 1:p1_uses_null=0; 1:r1=1; is_null=0; refcount=0;
Ok
Witnesses
Positive: 1 Negative: 2
Condition exists (refcount=0 /\ is_null=1 /\ 0:r0=1 /\ 1:r1=2 /\ 1:p1_uses_null=1)
Observation esdk-refcount Sometimes 1 2
Time esdk-refcount 0.01
Hash=4888acc962ad02eb5c4d73c0350e5c8c
```

The key line is “Ok” which says that an execution where `p1_uses_null==1` with `r0==1` and `r1==2` is possible. Herd gives the 3 states it has computed as being allowed (including the bad case). We also get an execution graph of the bad behavior.

![refcount](https://user-images.githubusercontent.com/52972368/63981029-6bd69280-ca8b-11e9-9eb4-bd4a225ce3f7.png)

Notice that there are `rf` (reads-from), `mo` (modification order) and `fr` (from-read) edges from event `d` (the atomic decrement of Thread B) to event `a` (the atomic decrement of Thread A) but there is not a happens-before edge (because event `a` is not an acquire).

If we fix the atomic as we suggest (making them acq_rel) then herd reports:

```
Test esdk-refcount-fixed Allowed
States 2
0:r0=1; 1:p1_uses_null=0; 1:r1=2; is_null=1; refcount=0;
0:r0=2; 1:p1_uses_null=0; 1:r1=1; is_null=0; refcount=0;
No
Witnesses
Positive: 0 Negative: 2
Condition exists (refcount=0 /\ is_null=1 /\ 0:r0=1 /\ 1:r1=2 /\ 1:p1_uses_null=1)
Observation esdk-refcount-fixed Never 0 2
Time esdk-refcount-fixed 0.01
Hash=ae23f7023c385a56b90cd123c24cf6f0
```

which excludes the bad case as intended.

**Comment by robin-aws** [comment]
Fixed by #433
