### ISSUE TITLE
Code does not compile against current aws-c-common

### ISSUE THREAD

**Issue by rmharris157** [aws/aws-encryption-sdk-c#450]
The current state of **aws-encryption-sdk-c** (b5cb473) does not compile against the head of **aws-c-common** (tested using clang 8 on FreeBSD 11 AMI) ...

```
[  8%] Building C object CMakeFiles/aws-encryption-sdk.dir/source/error.c.o

/home/ec2-user/aws-encryption-sdk-c/source/error.c:33:5: error: implicit declaration of function 'aws_load_error_strings' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
    aws_load_error_strings();
    ^
1 error generated.
```

the `aws_load_error_strings` function was removed from **aws-c-common** on commit  7639117 (between v0.4.4 and v0.4.5).

(I am also _roberhr@amazon.com_ if you have other questions.)

**Comment by dougch** [comment]
Correct, the README could use an upper bound on the version of c-common. Also see Issue #431 which has a link to the related PR.  This could be reprioritized after some of the build issues are resolved.

**Comment by rmharris157** [comment]
As per ragona@, additional context here: aws-c-io will not compile unless you have aws-c-common >= v0.4.7 (function aws_common_library_init) missing. This is incompatible with the requirement to compile aws-c-common above with required version before v0.4.5.

**Comment by dougch** [comment]
@rmharris157 can you clarify if your use case depends on aws-encryption-sdk-cpp ?

> As per ragona@, additional context here: aws-c-io will not compile unless you have aws-c-common >= v0.4.7 (function aws_common_library_init) missing. This is incompatible with the requirement to compile aws-c-common above with required version before v0.4.5.

**Comment by dougch** [comment]
While `current` is a moving target, pr/463 should unblock the heart of this request
