### ISSUE TITLE
macOs build and test jobs fail due to the update to Catalina (v10.15)

### ISSUE THREAD

**Issue by adpaco-aws** [aws/aws-encryption-sdk-c#650]
The macOs build and test jobs are failing due to an update to Catalina (v10.15): https://github.com/aws/aws-encryption-sdk-c/actions/runs/398191647

I have labeled this issue as "medium priority", but it is currently blocking ongoing PRs to be merged.

**Comment by alex-chew** [comment]
Looking at the logs of the build you linked, even on the macOS-14 environment, Actions is running our build on macOS 15:

```
Current runner version: '2.274.2'
Operating System
  Mac OS X
  10.15.7
  19H15
Virtual Environment
  Environment: macos-10.15
  Version: 20201130.3
  Included Software: https://github.com/actions/virtual-environments/blob/macOS-10.15/20201130.3/images/macos/macos-10.15-Readme.md
```

**Comment by alex-chew** [comment]
Looking at two consecutive builds [1] [2] from #643, where the first one failed and the second one succeeded, the successful build occurred on "Virtual Environment" version 20201115.1 [3], whereas the failed build occurred on Virtual Environment version 20201130.3 [4]. Notable software version changes include CMake 3.18.4 -> 3.19.1 [5] and XCode 12.0.1 -> 12.2 [6].

The failed build logs also contain a few instances of the message

```
CMake Warning (dev) at /usr/local/Cellar/cmake/3.19.1/share/cmake/Modules/ExternalProject.cmake:3346 (message):
  Policy CMP0114 is not set to NEW.  In order to support the Xcode "new build
  system", this project must be updated to set policy CMP0114 to NEW.

  Since CMake is generating for the Xcode "new build system",
  ExternalProject_Add will use policy CMP0114's NEW behavior anyway, but the
  generated build system may not match what the project intends.
Call Stack (most recent call first):
  cmake/BuildAwsCCommon.cmake:39 (ExternalProject_Add)
  CMakeLists.txt:19 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

which is described further in [5].

[1] https://github.com/aws/aws-encryption-sdk-c/runs/1484359349?check_suite_focus=true
[2] https://github.com/aws/aws-encryption-sdk-c/runs/1489483919?check_suite_focus=true
[3] https://github.com/actions/virtual-environments/blob/macOS-10.15/20201115.1/images/macos/macos-10.15-Readme.md
[4] https://github.com/actions/virtual-environments/blob/macOS-10.15/20201130.3/images/macos/macos-10.15-Readme.md
[5] https://cmake.org/cmake/help/latest/release/3.19.html
[6] https://github.com/actions/virtual-environments/issues/2056

**Comment by alex-chew** [comment]
@acioc tried out a local fresh build on macOS 10.14.6, using CMake 3.19.1 and Xcode version 11.3.1; the `cmake` commands for both aws-sdk-cpp and aws-encryption-sdk-c fail. So we think the CMake upgrade is the culprit.

**Comment by alex-chew** [comment]
The regression discussed in [1] and [2] might be related.

[1] https://discourse.cmake.org/t/error-when-installing-targets-and-exports-in-3-19-1/2245
[2] https://gitlab.kitware.com/cmake/cmake/-/issues/21529
