### ISSUE TITLE
missing include inside kms_mrk_keyring

### ISSUE THREAD

**Issue by marco-ceriani** [aws/aws-encryption-sdk-c#718]
### Problem:

In version 2.3.0 the file kms_mrk_keyring.h depends on the class KmsKeyring, but does not include its header, kms_keyring.h. This means that the compilation of projects that use this library depend on the specific order in which they include the two headers.

**Comment by alex-chew** [comment]
Hi macro-ceriani, thanks for reaching out. This looks accurate to me, I'll release a fixed version in the next few days and update this thread when it's ready.

**Comment by alex-chew** [comment]
Hi @marco-ceriani, just wanted to let you know that this fix is release in [v2.3.1](https://github.com/aws/aws-encryption-sdk-c/releases/tag/v2.3.1).

**Comment by marco-ceriani** [comment]
Hi Alex, thanks a lot
