### ISSUE TITLE
Add the DiscoveryFilter to the discovery keyring example

### ISSUE THREAD

**Issue by juneb** [aws/aws-encryption-sdk-c#736]
### Security issue notifications

If you discover a potential security issue in the AWS Encryption SDK we ask that you notify AWS Security via our [vulnerability reporting page](https://aws.amazon.com/security/vulnerability-reporting/). Please do **not** create a public GitHub issue.

### Problem:

The [discovery keyring example](https://github.com/aws/aws-encryption-sdk-c/blob/master/examples/kms_discovery.cpp),  is missing the best practice [DiscoveryFilter](https://github.com/aws/aws-encryption-sdk-c/blob/83db9a63335f063b71c9da964481f90e32d7fdc3/aws-encryption-sdk-cpp/include/aws/cryptosdk/cpp/kms_keyring.h#L35).

### Solution:

A description of the possible solution in terms of Encryption SDK architecture.

### Out of scope:

Is there anything the solution will intentionally NOT address?

[//]: #  (NOTE: If you believe this might be a security issue, please email aws-security@amazon.com instead of creating a GitHub issue. For more details, see the AWS Vulnerability Reporting Guide: https://aws.amazon.com/security/vulnerability-reporting/ )

**Comment by alex-chew** [comment]
This is resolved by #737.
