### ISSUE TITLE
MBedTLS support

### ISSUE THREAD

**Issue by disa6302** [aws/aws-encryption-sdk-c#745]
I see that this library depends on OpenSSL and uses OpenSSL libraries to support data encryption on device. Is there any plan to include support for MBedTLS as well since mBedTLS is pretty popular on embedded systems given its smaller memory footprint.

**Comment by alex-chew** [comment]
Hi @disa6302,

We don't have immediate plans to add support for MBedTLS. I'll leave this open as a feature request.
