### ISSUE TITLE
Rust support

### ISSUE THREAD

**Issue by aquanow-jeffen** [aws/aws-encryption-sdk-c#793]
Hello team,

Sorry not sure if this is the right place for general questions like this, please let me know.

Is there any plan to add Rust language support in the future? Or any suggestions about how to use this package on Rust?

Thanks

**Comment by ajewellamz** [comment]
We are actively working on Rust support in our libraries. We have not made any specific announcements about release dates.

Rust has support for Foreign Function Interfaces, and I suppose this C library could be used in that way.
